
##########################################
#     Change these variables !important
##########################################

# Set this for Copyright in the footer
owner: Maja

# Optional quote in the footer
# To disable set enable to false
quote:
  enable: true
  quote: You have to plan ahead and schedule everything so it's ready when you need it. Programming requires patience and the ability to handle detail. Women are 'naturals' at computer programming.
  author: Dr. Grace Hopper (1967)

# Set this to your main site title
# In the head - ff page doesnt have its own title,
# Site title will be used instead
title: Real IT Girl

# Description and title below nav in the header
punch-line: true

# Your logo for the header
logo:
  title: Real IT Girl
  subtitle: Blog o dievčati v IT

include:
  - pages

# Following needed for disqus integration
# Set your 'disqus' account name
disqus: realitgirl

# Uncomment if deployed locally
# url: https://localhost:4000

# Set your host if deployed not locally
# For example "https://yourGitHub.github.io"
url: "https://realitgirl.github.io"

# Change this to your base URL starting with forward slash if site is in gh-pages branch
# For example /branchName
baseurl:

# Change this to your google analytics ID
google_analytics: UA-79723666-1

# Contact form pupublic key
contact_PK:

##########################################
#          Optional variables
##########################################


# Set maximum posts per page
paginate: 5

# Set permalink
permalink: /:categories/:title

# Set excerpt separator
truncate_size: 40

##########################################
#          Do not change these variables
##########################################

sass:
  sass_dir: _sass
sass:
    style: compressed

include:
  - pages

gems:
  - jekyll-paginate
  - jekyll-sitemap # add /sitemap.xml file

paginate_path: /_pages/page:num

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
